Werewolf for Telegram/Languages/Deutsch.xml
looked through all the german strings, tried to match them to the english ones and fixed grammar, stelling and punctuation errors (and probably introduced some myself :P). will have a look again tomorrow to fix any i've missed
=> updated german translation

Werewolf for Telegram/Werewolf Node/Werewolf.cs
=> Made Day a translatable string

Werewolf for Telegram/Werewolf Node/Werewolf.cs
.GetName() already does its work
=> Deleted usernames when not necessary

README.md
- Steps 1 to 3's documentations have been refined.
=> README.md: Detailed Explanations

Werewolf for Telegram/Werewolf Control/Commands/HelpCommands.cs
So that non-english players can understand roles.
Also, now roles are sorted by order of appearance in normal games.
=> Added emojis to /rolelist

Werewolf for Telegram/Languages/English.xml, Werewolf for Telegram/Werewolf Control/Handlers/UpdateHandler.cs
Translator found "not" a problem in those strings. I tried to rearrange the sentence so that "not" is not needed
=> Trying to fix 'not' problem in AllowFlee

Werewolf for Telegram/Werewolf Node/Werewolf.cs
By the way I'm not sure if I checked more things than I should have, but
this should work anyways.
Fix #106
=> Fix dead & fled people getting LongHaul

Werewolf for Telegram/Werewolf Node/Werewolf.cs
=> Order of players is not alphabetic anymore in the menus

Werewolf for Telegram/Werewolf Control/Commands/GameCommands.cs
=> Make admins able to forcestart even if not in game

Werewolf for Telegram/Werewolf Node/Werewolf.cs
This won't change much actually, but if someone wants to clone it and change GameJoinTime...
=> Use Settings.GameJoinTime for join timer

Werewolf for Telegram/Werewolf Node/Models/IPlayer.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs
Details of the changes are in commit messages. Basically, there is no real change in the overall behaviour of the bot, but there are some little fixes, and this should (kind of) tidy up the code for in-group death messages after night.
I commented (almost) all of the old code, so that it shouldn't be difficult to revert only some of the changes. I know that maybe I should have made more different minor commits and this would have helped... but I just worked at all those things together so I couldn't think of it.
A posteriori, I don't know if it was really worth it (XD)... but anyway, merging it shouldn't be that bad.
P.S. I realize old code comments could be a bit annoying.. I'll delete them as soon as you merge the PR, if you want to.
=> Some (kind of) refactoring

Werewolf for Telegram/Languages/English.xml, Werewolf for Telegram/Werewolf Control/Commands/DevCommands.cs, Werewolf for Telegram/Werewolf Control/Commands/GameCommands.cs, Werewolf for Telegram/Werewolf Control/Commands/GeneralCommands.cs, Werewolf for Telegram/Werewolf Control/Handlers/UpdateHandler.cs, Werewolf for Telegram/Werewolf Control/Helpers/LanguageHelper.cs, Werewolf for Telegram/Werewolf Control/Helpers/UpdateHelper.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs
Some very little commits that need your review/approval before being pushed.
=> New commits

Werewolf for Telegram/Werewolf Node/Werewolf.cs
Smart Gunner Achievement did not check for gunner killing Alpha and Cub
=> Fix Checking for SmartGunner Achivement

Werewolf for Telegram/Werewolf Node/Helpers/Extensions.cs
I've made separate commits so that you can `cherry-pick` / `reverse` what you want.
=> Some proposals for balancing

Werewolf for Telegram/Werewolf Node/Models/IPlayer.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs
=> Create StreetWise Achievement

Werewolf for Telegram/Languages/English.xml, Werewolf for Telegram/Languages/FurryNSFW.xml, Werewolf for Telegram/Werewolf Node/Werewolf.cs
Just seems to be a logical change event. Could happen on occasion of silverspread night for example
This change adds a new String for all language files though, have set up two as example
=> Cult dies if they visit when Wolf is at home

Werewolf for Telegram/Werewolf Node/Werewolf.cs
voteCult and voteWolves check should be 0 and -1
=> Fix voteCult and voteWolves skip-check in cult-night

Werewolf for Telegram/Languages/English.xml, Werewolf for Telegram/Werewolf Node/Werewolf.cs
This increases readability, plus speeds up CH vs Cultist (-> CH kills last Cultist and VG wins) and Hunter vs Wolf (30% chance: Hunter kills Wolf and VG wins, 70% chance: Wolf kills Hunter and Wolves win) finales.
=> A bit of refactoring in CheckForGameEnd()

Werewolf for Telegram/Werewolf Node/Werewolf.cs
There was a space missing that really annoyed us translators... so i added it.
=> Added a missing space xP

Werewolf for Telegram/Werewolf Website/Views/Home/Index.cshtml
Added that wolves have a 20% chance to eat the serial killer
=> Correct sk string on website

Werewolf for Telegram/Database/Achievements.cs, Werewolf for Telegram/Werewolf Node/Models/IPlayer.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs
Re-submit of #256 because of poor git history
Added below new achievements, suggested by some Hong Kong players
The numbers, Achievement Names and Descriptions can be changed accordingly.
**No Sorcery!**
_As a wolf, kill your sorcerer_
**Cultest Tracker**
_As the cultist hunter, kill at least 3 cultists in one game_
**I'M NOT DRUN-- \*BURPPP\***
_As the clumsy guy, have at least 3 correct lynches by the end of the game_
**Wuffie-Cult**
_As the alpha wolf, successfully convert at least 3 victims into wolves_
**Did you guard yourself?**
_As the guardian angel, survive after 3 tries guarding an unattacked wolf_
**Spoiled Rich Brat**
_As the prince, still gets lynched even after revealing your identity_
**Three Little Wolves and a Big Bad Pig**
_As the sorcerer, survive a game with three or …
=> New Achievements

Werewolf for Telegram/Database/Achievements.cs, Werewolf for Telegram/Werewolf Node/Models/IPlayer.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs
Reverts GreyWolfDev/Werewolf#257
=> Revert "New Achievements"

Werewolf for Telegram/Werewolf Control/Commands/AdminCommands.cs, Werewolf for Telegram/Werewolf Control/Commands/DevCommands.cs, Werewolf for Telegram/Werewolf Control/Commands/GeneralCommands.cs, Werewolf for Telegram/Werewolf Control/Commands/Helpers.cs
Fix on preferred/setlink and error logging on join
=> Fix on preferred/setlink and error logging on join

Werewolf for Telegram/Database/Achievements.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs
typo fix for 2 achievements
remove extra check for 3nights achievement
=> Fix for 2 new achievements

Werewolf for Telegram/Werewolf Node/Werewolf.cs
I just forked this to one of my organizations bcs i couldnt find how to delete all those commits, sorry
=> Fix a problem where a player never sent a message, joined a game and was almost unbannable.

Werewolf for Telegram/Werewolf Control/Commands/AdminCommands.cs
Slowed down the sending of gifs to be friendly to the api
Send a heading before sending the gifs to separate users.
=> Modified gif review sending

README.md
It was moved to the registry, isn't it?
=> The database connection string

Werewolf for Telegram/Werewolf Node/Werewolf.cs
Did we never realise the day time is actually using the lynch time?
=> Fix day time actually used lynch time

Werewolf for Telegram/Werewolf Node/Werewolf.cs
Fix "I Helped" was actually granted to DG if the DG's rm is the cub
Add Long Haul Check at DoGameEnd()
=> Fix "I Helped" achv and add Long Haul Check at game end

Werewolf for Telegram/Werewolf Node/Werewolf.cs
now only the cub who died last would get it, not about dg or not
=> Fix "I Helped" again

Werewolf for Telegram/Werewolf Control/Commands/GeneralCommands.cs
So players don't have to ask group admins to do it all the time
=> Add a command to get own idles

Werewolf for Telegram/Werewolf Control/Commands/AdminCommands.cs, Werewolf for Telegram/Werewolf Control/Commands/DevCommands.cs, Werewolf for Telegram/Werewolf Control/Commands/GifCommands.cs, Werewolf for Telegram/Werewolf Control/Commands/HelpCommands.cs
- Fix beta disabled commands (the commands need to be compiled so it will show the NotGlobalAdmin / NotPara message anyway)
- Re-enable the grouplist in general
- Make the grouplist for persian lang base unaccessible
Please merge into master and beta
=> Some changes

Werewolf for Telegram/Werewolf Website/Controllers/StatsController.cs
Two chars can really fuck up some code
=> Fixed wrong number of times killed in json

Werewolf for Telegram/Werewolf Node/Werewolf.cs
There is a bug that causes some games to start with 2 lycan, this should fix it
=> Fix double lycan

Werewolf for Telegram/Werewolf Control/Commands/AdminCommands.cs
Changed the descripition from Tanner Start to Tanner Win now
=> Small update

Werewolf for Telegram/Database/AchievementsReworked.cs, Werewolf for Telegram/Werewolf Node/Helpers/Extensions.cs, Werewolf for Telegram/Werewolf Node/Helpers/SpecialStrings.cs, Werewolf for Telegram/Werewolf Node/Models/IPlayer.cs, Werewolf for Telegram/Werewolf Node/Models/QuestionAsked.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs, Werewolf for Telegram/Werewolf Node/WerewolfNode.csproj
=> Add new role Spumpkin

Werewolf for Telegram/Werewolf Control/Helpers/LanguageHelper.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs
Primary fallback to default of language base, Secondary fallback to english
=> Double Language Fallback

Werewolf for Telegram/Database/GroupConfig.cs, Werewolf for Telegram/Werewolf Control/Handlers/UpdateHandler.cs
Config menu will now be ordered into subgroups instead of all options being on one big page.
=> Reworked Config Menu

Werewolf for Telegram/Werewolf Node/Models/IPlayer.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs
Reverts GreyWolfDev/Werewolf#418
=> Revert "Valentines cpu fix (hopefully)"

Werewolf for Telegram/Database/Achievements.cs, Werewolf for Telegram/Database/AchievementsReworked.cs, Werewolf for Telegram/Database/Database.csproj, Werewolf for Telegram/Werewolf Control/Commands/DevCommands.cs, Werewolf for Telegram/Werewolf Control/Handlers/UpdateHandler.cs, Werewolf for Telegram/Werewolf Control/Helpers/Bot.cs, Werewolf for Telegram/Werewolf Control/Helpers/LanguageHelper.cs, Werewolf for Telegram/Werewolf Control/Models/InlineCommand.cs, Werewolf for Telegram/Werewolf Control/Program.cs, Werewolf for Telegram/Werewolf Node/Helpers/Extensions.cs, Werewolf for Telegram/Werewolf Node/Models/IPlayer.cs, Werewolf for Telegram/Werewolf Node/Program.cs, Werewolf for Telegram/Werewolf Node/Werewolf.cs
Reverts GreyWolfDev/Werewolf#440
=> Revert "A little bit of code improvement"

Werewolf for Telegram/Werewolf Node/Werewolf.cs
Sk victims not being shown properly (and probably victims of certain other roles too)
=> Fixes to multiple bugs

Werewolf for Telegram/Werewolf Control/Commands/DevCommands.cs
Now the super secret command called /customgif is not secret anymore :P
=> New Description for GIF unlock

Werewolf for Telegram/Werewolf Node/Werewolf.cs
Edit the message after the hunter's time expires and he does not select.
=> Hunter bug fixed

Werewolf for Telegram/Werewolf Node/Werewolf.cs
An extra backslash removed and one forgotten line of text added.
=> Edit win message

Werewolf for Telegram/Werewolf Control/Commands/AdminCommands.cs
=> Added "Start Me" message to /config
