GreyWolfDev/Werewolf

Werewolf for Telegram/Werewolf Control/Commands/Helpers.cs

..because they obviously already know if a game started

Don't notify who did /startgame

---

Werewolf for Telegram/Werewolf Control/Commands/GeneralCommands.cs

People were registered with the "/start" message id instead of their Telegram id. Not a big issue for the algorithm, but this would save a bit of space in the database

Fix /start command adding people in DB multiple times

---

Werewolf for Telegram/Werewolf Node/Models/IPlayer.cs
Werewolf for Telegram/Werewolf Node/Werewolf.cs

There is a small dupe bug when the GA guards a wolf on the same night the wolf decides to eat the GA. The GA death message goes out immediately but nothing is set to indicate that the GA is already dead, so a second GA death message is sent during the start of DayCycle(). This patch corrects this by setting a new value, DiedGuardingWolf, to true during the night cycle and checking to make sure it's false during DayCycle to prevent the dupe.
TG: @GRAVYLORD

Fix for GA/Wolf Kill Message Duping

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

The HeyManNiceShot achievement did not check for hunter killing Alpha and Cub

Fix Checking of HeyManNiceShot Achievement

---

Werewolf for Telegram/Werewolf Control/Commands/GeneralCommands.cs

Suggested by @Peterpaiter, seeing as the website has no translated role explanations. Now using the /help command will return a message with the previous links, plus the /rolelist command.

Add /rolelist to the help command

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

Fix when DG turned Traitor, turned to wolf directly while there is still alive alpha/cub

Fix DG->Traitor->Wolf's check for alive alpha/cub

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

Currently the Clumsy Guy always lynches randomly (might randomly lynch the one he actually selects) because of the broken always true conditional. Fixed the conditional.

Correct Clumsy Guy random lynching every turn. Fixes #184

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

For https://github.com/parabola949/Werewolf/commit/def4b178f48d599ca63702f416feb3826ae021b3
added CheckRoleChanges at NightCycle so for example appseer would promote when the seer is alpha-converted
For https://github.com/parabola949/Werewolf/commit/96a4dc1616b9d513640a6407fc3e2d3b6166c34d
If AppSeer (or even Cursed) turned wolf before dying, DG should turn to their original role instead of directly into wolf, Para please decide if its well-balanced for these 2 roles to have such behaviour

Fixes about Role Changes

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

When gunner shot default, it looked like this:
Suddenly, a shot rings out.  The village turns to see {hunter} standing over {player}'s body, a gun still aimed at the head. a Werewolf 🐺 is dead.
The "a" in "a werewolf" was lowercase, because the "Wolf"-String was called (of course it could be any role). It also cannot just be made uppercase in the langfile, because it is also used in "{player} was {role}" and then it would look like that: "{player} was A werewolf". What I did is quiet much the same as #210, I replaced "IsDead" by "Was", so the dead player's name is the first word in the sentence.

Fixed lowercase at the beginning of a sentence by calling different strings

---

Werewolf for Telegram/Werewolf Control/Handlers/UpdateHandler.cs
Werewolf for Telegram/Werewolf Control/Helpers/Settings.cs

Sometimes, games are accidently started in translation group and admins don't see the files to upload anymore. Since the group is not for playing games, I'd avoid games there.

Don't allow games in translation group

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

This time, `DefaultKilled`. The sentence began with a lowercase if the description of the role began with a lowercase. (Basiacally, same change as in #210 and #211)

Fixing another lowercase at beginning of a sentence XD

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

Fix for the fact that CheckForGameEnd() only tests if a player was bitten by the Alpha Wolf when checking if the traitor should turn into a wolf, not when checking if the village has won. This would lead to games ending in a village victory when there should have been a bitten player turning into a wolf.

Properly check for bitten in CheckForGameEnd()

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

Counter does not need to be reset I guess. Achievement description says be the first to cast a lynch vote 5 times in a single game and not in a row. If not we can change the description instead. :smile_cat:

First Stone fix

---

Werewolf for Telegram/Werewolf Control/Commands/AdminCommands.cs

When trying to upload non-xml files, global admins get a confusing error message yet, so better avoid that codewise :)

Don't upload non-xml files

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

There was a small problem with my previous pull request, I forgot the brackets so the bot was generating the same random wolf role several times. I'm sorry, it should be fine now.

Fix double lycan (brackets were missing)

---

Werewolf for Telegram/Werewolf Node/Werewolf.cs

There is a rare bug that caused some games to start with appseer but no seer. It doesn't happen very often, but when it does, it's very confusing. The appseer turns into seer before the first night even ended. The reason for this bug was this one:
The balancing of the rolelist first checked if there was seer when there was appseer, then checked if there was cultist hunter when there is cult. This last step would remove a village role to make room for cultist hunter, so seer could be removed. 
The bug would happen when the original role list has appseer, seer and cult (but no CH), and the random village role chosen to become ch was the seer.
I fixed the bug by just changing the order. It now checks for CH first, then for seer, to make sure the game never starts with AppSeer without Seer.

Fixing AppSeer without Seer bug

---

Werewolf for Telegram/Werewolf Node/Helpers/Extensions.cs

Arsonist is a cool role but kinda weak in comparison to even normal wolf
Giving that high strength causes imbalance in games.. especially smaller ones

Reduce strength of Arsonist for balance

---

Werewolf for Telegram/Werewolf Control/Handlers/UpdateHandler.cs

Buttons were already using private language, but not messages.

Return group config’s messages in user’s private language

---

Werewolf for Telegram/Werewolf Control/Commands/AdminCommands.cs

Handle new telegram invite link format :
`https://telegram.me/+[XXXXXXXXXX]` and/or `https://t.me/+[XXXXXXXX]`

Fix: Handle new telegram invite link format for setlink

---

Werewolf for Telegram/Werewolf Control/Attributes/Command.cs
Werewolf for Telegram/Werewolf Control/Commands/AdminCommands.cs
Werewolf for Telegram/Werewolf Control/Commands/GameCommands.cs
Werewolf for Telegram/Werewolf Control/Handlers/UpdateHandler.cs
Werewolf for Telegram/Werewolf Control/Helpers/Bot.cs
Werewolf for Telegram/Werewolf Control/Models/Command.cs

As in title.
In addition, now the anonymous admin check does not rely on the fake ID returned by the BotAPI for backwards compatibility, and anonymous channels are asked to exit that mode too (it might be necessary to reword the corresponding string a bit however).

Allow anonymous admins to use /smite, /getidles
